### ISSUE TITLE
Incorrect row/column switching in cpr.py

### ISSUE THREAD

**Issue by krauthor** [Qcactus/CPR#5]
In the file `cpr.py`, the code on line 38 is supposed to switch columns, but is, to my understanding, switching rows. 
https://github.com/Qcactus/CPR/blob/782edb82ea8e996071807a9e5c5f9ef1c477e6ce/recq/recommenders/cpr.py#L38

This is causing incorrect model behavior. According to equation (13) of the paper and line 7 of the pseudo-algorithm, the procedure should switch the first item of the tuple to the last positon of each tuple. Each row of `i_list` seems to contain the concatenated embedding vectors of all `idx + 2` items of the tuple. So its shape is `(idx + 2)*embed_size`. Hence, we should be shifting the first `embed_size` columns to the end.

To fix this issue, the code should be changed to switch the first `embed_size` columns to the end instead of the first row.

This issue was discovered during testing of the `cpr.py` file, and appears to be affecting model training. For validation, I tried to input a shifted item sequence directly and computed `pos_scores`. They should have been identical to `neg_scores` of the non-shifted sequence but they were not.

Apologies if I have misunderstood your code and there is no error. Please let me know if you require any additional information.

**Comment by Qcactus** [comment]
It's been a while since I wrote this code, so I'm sorry I can't recall all the details. But based on what you described, I think the switching is correct here. The `(idx + 2)*embed_size` shape is the shape of i_list before the execution of [line 27](https://github.com/Qcactus/CPR/blob/782edb82ea8e996071807a9e5c5f9ef1c477e6ce/recq/recommenders/cpr.py#L27). After this line, i_list becomes a list of tensors, each of which is a column of the original tensor. So, `i_list[0]` means the first column of the original tensor and it is switched to the end.
